// <auto-generated />
using System;
using Cs2Highlight.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cs2Highlight.Web.Data.Migrations
{
    [DbContext(typeof(GenerationDbContext))]
    [Migration("20260730113422_Stage8_2InteractiveTimelineDirector")]
    partial class Stage8_2InteractiveTimelineDirector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Generation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectPreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("EstimatedDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinalVideoArtifactId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GenerationCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GenerationStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumHighlights")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumScore")
                        .HasColumnType("REAL");

                    b.Property<string>("OutputOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PriceAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPlayerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedSteamId")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransitionDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransitionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationArtifact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("GenerationArtifacts");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationBrollCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActionDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("CinematicScore")
                        .HasColumnType("REAL");

                    b.Property<long>("EndTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationDemoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MovementScore")
                        .HasColumnType("REAL");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrajectoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationDemoId");

                    b.HasIndex("GenerationId", "CandidateId")
                        .IsUnique();

                    b.ToTable("GenerationBrollCandidates");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationCameraShot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FallbackType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FovEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("FovStart")
                        .HasColumnType("REAL");

                    b.Property<long?>("GenerationBrollCandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyframesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviewAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShotId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationBrollCandidateId");

                    b.HasIndex("GenerationId", "ShotId")
                        .IsUnique();

                    b.ToTable("GenerationCameraShots");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationCinematicPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicExcerptJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannerVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("GenerationCinematicPlans");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationDemo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TickRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "Sha256")
                        .IsUnique();

                    b.ToTable("GenerationDemos");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEditSegment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseSpeedFactor")
                        .HasColumnType("REAL");

                    b.Property<long>("GenerationHighlightId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MatchScore")
                        .HasColumnType("REAL");

                    b.Property<string>("MusicalAnchorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputStartMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrimaryKillOutputMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoreBreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeWarpPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransitionIn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransitionOut")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationHighlightId");

                    b.HasIndex("GenerationId", "Sequence")
                        .IsUnique();

                    b.ToTable("GenerationEditSegments");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEffectPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeterministicSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DynamicEffectPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationHighlightId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Preset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimelineJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationHighlightId");

                    b.HasIndex("GenerationId", "GenerationHighlightId")
                        .IsUnique();

                    b.ToTable("GenerationEffectPlans");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("GenerationEvents");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationHighlight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BeautyScore")
                        .HasColumnType("REAL");

                    b.Property<double>("CombatScore")
                        .HasColumnType("REAL");

                    b.Property<int?>("CompilationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EstimatedDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstKillTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationDemoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeadshotCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HighlightId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("KillCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastKillTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("PrimaryKillTick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RoundStartTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SafeEndTick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("ScoreBreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SelectedByUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SelectedForCompilation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TickRate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponSequenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "GenerationDemoId", "HighlightId")
                        .IsUnique();

                    b.ToTable("GenerationHighlights");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMovieSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticCinematicCameras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CinematicDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CinematicEditIntensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorGradePreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectIntensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectPlannerVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnabledEffectGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GameplayGainDb")
                        .HasColumnType("REAL");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LutAssetKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicDurationPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MusicGainDb")
                        .HasColumnType("REAL");

                    b.Property<string>("SyncIntensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransitionPreference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("GenerationMovieSettings");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AnalysisArtifactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisSchemaVersion")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RightsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RightsConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<double?>("TempoBpm")
                        .HasColumnType("REAL");

                    b.Property<double?>("TempoConfidence")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("GenerationMusic");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusicAnchor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnchorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.Property<long>("TimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "AnchorId")
                        .IsUnique();

                    b.ToTable("GenerationMusicAnchors");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusicSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BassEnergy")
                        .HasColumnType("REAL");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("EndMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Energy")
                        .HasColumnType("REAL");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RhythmicDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "SectionId")
                        .IsUnique();

                    b.ToTable("GenerationMusicSections");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalKills")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "SteamId")
                        .IsUnique();

                    b.ToTable("GenerationPlayers");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineAnchor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnchorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedPostRollSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("EstimatedPreRollSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FeasibilityStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarkerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredBaseSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredLocalSpeed")
                        .HasColumnType("REAL");

                    b.Property<long>("TargetMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimelinePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimelinePlanId", "AnchorId")
                        .IsUnique();

                    b.ToTable("GenerationTimelineAnchors");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineGap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GapId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextAnchorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousAnchorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimelinePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimelinePlanId", "GapId")
                        .IsUnique();

                    b.ToTable("GenerationTimelineGaps");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelinePlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExcerptEndMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExcerptStartMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionCursor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("GenerationTimelinePlans");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimelinePlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimelinePlanId", "Number")
                        .IsUnique();

                    b.ToTable("GenerationTimelineRevisions");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationArtifact", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Artifacts")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationBrollCandidate", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationDemo", "Demo")
                        .WithMany()
                        .HasForeignKey("GenerationDemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("BrollCandidates")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demo");

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationCameraShot", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationBrollCandidate", "BrollCandidate")
                        .WithMany()
                        .HasForeignKey("GenerationBrollCandidateId");

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("CameraShots")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrollCandidate");

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationCinematicPlan", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithOne("CinematicPlan")
                        .HasForeignKey("Cs2Highlight.Web.Domain.GenerationCinematicPlan", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationDemo", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Demos")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEditSegment", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationHighlight", "Highlight")
                        .WithMany()
                        .HasForeignKey("GenerationHighlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("EditSegments")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Highlight");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEffectPlan", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationHighlight", "Highlight")
                        .WithMany()
                        .HasForeignKey("GenerationHighlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("EffectPlans")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Highlight");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEvent", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Events")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationHighlight", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Highlights")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMovieSettings", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithOne("MovieSettings")
                        .HasForeignKey("Cs2Highlight.Web.Domain.GenerationMovieSettings", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusic", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithOne("Music")
                        .HasForeignKey("Cs2Highlight.Web.Domain.GenerationMusic", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusicAnchor", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("MusicAnchors")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusicSection", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("MusicSections")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationPlayer", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Players")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineAnchor", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationTimelinePlan", "TimelinePlan")
                        .WithMany("Anchors")
                        .HasForeignKey("TimelinePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimelinePlan");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineGap", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationTimelinePlan", "TimelinePlan")
                        .WithMany("Gaps")
                        .HasForeignKey("TimelinePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimelinePlan");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelinePlan", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithOne("TimelinePlan")
                        .HasForeignKey("Cs2Highlight.Web.Domain.GenerationTimelinePlan", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineRevision", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationTimelinePlan", "TimelinePlan")
                        .WithMany("Revisions")
                        .HasForeignKey("TimelinePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimelinePlan");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Payment", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Payments")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Generation", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("BrollCandidates");

                    b.Navigation("CameraShots");

                    b.Navigation("CinematicPlan");

                    b.Navigation("Demos");

                    b.Navigation("EditSegments");

                    b.Navigation("EffectPlans");

                    b.Navigation("Events");

                    b.Navigation("Highlights");

                    b.Navigation("MovieSettings");

                    b.Navigation("Music");

                    b.Navigation("MusicAnchors");

                    b.Navigation("MusicSections");

                    b.Navigation("Payments");

                    b.Navigation("Players");

                    b.Navigation("TimelinePlan");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelinePlan", b =>
                {
                    b.Navigation("Anchors");

                    b.Navigation("Gaps");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
