// <auto-generated />
using System;
using Cs2Highlight.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cs2Highlight.Web.Data.Migrations
{
    [DbContext(typeof(GenerationDbContext))]
    [Migration("20260803114602_ActiveStageKey")]
    partial class ActiveStageKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Cs2Highlight.Web.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReferralRewardedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferrerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("redline");

                    b.Property<int>("TokenBalance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Generation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveStageKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("CleanupAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CleanupCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanupError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CleanupStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanupStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("DeletedTemporaryBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EffectPreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("EstimatedDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinalVideoArtifactId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GenerationCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GenerationStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumHighlights")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumScore")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("OutputDeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PriceAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessingDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("QueueDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("QueueEnteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedPlayerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedSteamId")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TemporaryBytesPeak")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TokenRefunded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransitionDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransitionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationArtifact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("GenerationArtifacts");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationBrollCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActionDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("CinematicScore")
                        .HasColumnType("REAL");

                    b.Property<long>("EndTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationDemoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MovementScore")
                        .HasColumnType("REAL");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrajectoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationDemoId");

                    b.HasIndex("GenerationId", "CandidateId")
                        .IsUnique();

                    b.ToTable("GenerationBrollCandidates");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationCameraShot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FallbackType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FovEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("FovStart")
                        .HasColumnType("REAL");

                    b.Property<long?>("GenerationBrollCandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyframesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviewAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShotId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationBrollCandidateId");

                    b.HasIndex("GenerationId", "ShotId")
                        .IsUnique();

                    b.ToTable("GenerationCameraShots");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationCinematicPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicExcerptJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannerVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("GenerationCinematicPlans");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationDemo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TickRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "Sha256")
                        .IsUnique();

                    b.ToTable("GenerationDemos");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEditSegment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseSpeedFactor")
                        .HasColumnType("REAL");

                    b.Property<long>("GenerationHighlightId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MatchScore")
                        .HasColumnType("REAL");

                    b.Property<string>("MusicalAnchorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputStartMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrimaryKillOutputMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoreBreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeWarpPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransitionIn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransitionOut")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationHighlightId");

                    b.HasIndex("GenerationId", "Sequence")
                        .IsUnique();

                    b.ToTable("GenerationEditSegments");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEffectPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeterministicSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DynamicEffectPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationHighlightId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Preset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimelineJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationHighlightId");

                    b.HasIndex("GenerationId", "GenerationHighlightId")
                        .IsUnique();

                    b.ToTable("GenerationEffectPlans");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("GenerationEvents");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationHighlight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BeautyScore")
                        .HasColumnType("REAL");

                    b.Property<double>("CombatScore")
                        .HasColumnType("REAL");

                    b.Property<int?>("CompilationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EstimatedDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstKillTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationDemoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeadshotCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HighlightId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("KillCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastKillTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("PrimaryKillTick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RoundStartTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SafeEndTick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("ScoreBreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SelectedByUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SelectedForCompilation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TickRate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponSequenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "GenerationDemoId", "HighlightId")
                        .IsUnique();

                    b.ToTable("GenerationHighlights");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMovieSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticCinematicCameras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CinematicDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CinematicEditIntensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorGradePreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectIntensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectPlannerVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnabledEffectGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GameplayGainDb")
                        .HasColumnType("REAL");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LutAssetKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicDurationPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MusicGainDb")
                        .HasColumnType("REAL");

                    b.Property<string>("SyncIntensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransitionPreference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("GenerationMovieSettings");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AnalysisArtifactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisSchemaVersion")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RightsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RightsConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<double?>("TempoBpm")
                        .HasColumnType("REAL");

                    b.Property<double?>("TempoConfidence")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("GenerationMusic");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusicAnchor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnchorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.Property<long>("TimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "AnchorId")
                        .IsUnique();

                    b.ToTable("GenerationMusicAnchors");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusicSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BassEnergy")
                        .HasColumnType("REAL");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("EndMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Energy")
                        .HasColumnType("REAL");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RhythmicDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "SectionId")
                        .IsUnique();

                    b.ToTable("GenerationMusicSections");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalKills")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "SteamId")
                        .IsUnique();

                    b.ToTable("GenerationPlayers");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineAnchor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnchorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedPostRollSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("EstimatedPreRollSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FeasibilityStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarkerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredBaseSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredLocalSpeed")
                        .HasColumnType("REAL");

                    b.Property<long>("TargetMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimelinePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimelinePlanId", "AnchorId")
                        .IsUnique();

                    b.ToTable("GenerationTimelineAnchors");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineGap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GapId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextAnchorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousAnchorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimelinePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimelinePlanId", "GapId")
                        .IsUnique();

                    b.ToTable("GenerationTimelineGaps");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelinePlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExcerptEndMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExcerptStartMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionCursor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("GenerationTimelinePlans");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimelinePlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimelinePlanId", "Number")
                        .IsUnique();

                    b.ToTable("GenerationTimelineRevisions");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Referral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferredUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferrerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RewardedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferredUserId")
                        .IsUnique();

                    b.HasIndex("ReferrerUserId", "ReferredUserId")
                        .IsUnique();

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.TokenPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("PriceAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TokenPackages");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.TokenPurchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TokenPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.HasIndex("TokenPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("TokenPurchases");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.TokenTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReferralId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TokenPurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("ReferralId");

                    b.HasIndex("TokenPurchaseId");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("TokenTransactions");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.UserConsent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConsentType", "DocumentVersion")
                        .IsUnique();

                    b.ToTable("UserConsents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Generation", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", "User")
                        .WithMany("Generations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationArtifact", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Artifacts")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationBrollCandidate", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationDemo", "Demo")
                        .WithMany()
                        .HasForeignKey("GenerationDemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("BrollCandidates")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demo");

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationCameraShot", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationBrollCandidate", "BrollCandidate")
                        .WithMany()
                        .HasForeignKey("GenerationBrollCandidateId");

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("CameraShots")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrollCandidate");

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationCinematicPlan", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithOne("CinematicPlan")
                        .HasForeignKey("Cs2Highlight.Web.Domain.GenerationCinematicPlan", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationDemo", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Demos")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEditSegment", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationHighlight", "Highlight")
                        .WithMany()
                        .HasForeignKey("GenerationHighlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("EditSegments")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Highlight");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEffectPlan", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationHighlight", "Highlight")
                        .WithMany()
                        .HasForeignKey("GenerationHighlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("EffectPlans")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Highlight");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEvent", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Events")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationHighlight", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Highlights")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMovieSettings", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithOne("MovieSettings")
                        .HasForeignKey("Cs2Highlight.Web.Domain.GenerationMovieSettings", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusic", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithOne("Music")
                        .HasForeignKey("Cs2Highlight.Web.Domain.GenerationMusic", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusicAnchor", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("MusicAnchors")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationMusicSection", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("MusicSections")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationPlayer", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Players")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineAnchor", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationTimelinePlan", "TimelinePlan")
                        .WithMany("Anchors")
                        .HasForeignKey("TimelinePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimelinePlan");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineGap", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationTimelinePlan", "TimelinePlan")
                        .WithMany("Gaps")
                        .HasForeignKey("TimelinePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimelinePlan");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelinePlan", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithOne("TimelinePlan")
                        .HasForeignKey("Cs2Highlight.Web.Domain.GenerationTimelinePlan", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelineRevision", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationTimelinePlan", "TimelinePlan")
                        .WithMany("Revisions")
                        .HasForeignKey("TimelinePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimelinePlan");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Payment", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Payments")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Referral", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", "ReferredUser")
                        .WithMany()
                        .HasForeignKey("ReferredUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", "ReferrerUser")
                        .WithMany()
                        .HasForeignKey("ReferrerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferredUser");

                    b.Navigation("ReferrerUser");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.TokenPurchase", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.TokenPackage", "TokenPackage")
                        .WithMany()
                        .HasForeignKey("TokenPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", "User")
                        .WithMany("TokenPurchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.TokenTransaction", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cs2Highlight.Web.Domain.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cs2Highlight.Web.Domain.TokenPurchase", "TokenPurchase")
                        .WithMany()
                        .HasForeignKey("TokenPurchaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", "User")
                        .WithMany("TokenTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Referral");

                    b.Navigation("TokenPurchase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.UserConsent", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", "User")
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.ApplicationUser", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Generations");

                    b.Navigation("TokenPurchases");

                    b.Navigation("TokenTransactions");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Generation", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("BrollCandidates");

                    b.Navigation("CameraShots");

                    b.Navigation("CinematicPlan");

                    b.Navigation("Demos");

                    b.Navigation("EditSegments");

                    b.Navigation("EffectPlans");

                    b.Navigation("Events");

                    b.Navigation("Highlights");

                    b.Navigation("MovieSettings");

                    b.Navigation("Music");

                    b.Navigation("MusicAnchors");

                    b.Navigation("MusicSections");

                    b.Navigation("Payments");

                    b.Navigation("Players");

                    b.Navigation("TimelinePlan");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationTimelinePlan", b =>
                {
                    b.Navigation("Anchors");

                    b.Navigation("Gaps");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
