// <auto-generated />
using System;
using Cs2Highlight.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cs2Highlight.Web.Data.Migrations
{
    [DbContext(typeof(GenerationDbContext))]
    partial class GenerationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Generation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectPreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("EstimatedDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinalVideoArtifactId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GenerationCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GenerationStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumHighlights")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumScore")
                        .HasColumnType("REAL");

                    b.Property<string>("OutputOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PriceAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPlayerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedSteamId")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransitionDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransitionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationArtifact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("GenerationArtifacts");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationDemo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TickRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "Sha256")
                        .IsUnique();

                    b.ToTable("GenerationDemos");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEffectPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationHighlightId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Preset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimelineJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationHighlightId");

                    b.HasIndex("GenerationId", "GenerationHighlightId")
                        .IsUnique();

                    b.ToTable("GenerationEffectPlans");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("GenerationEvents");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationHighlight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BeautyScore")
                        .HasColumnType("REAL");

                    b.Property<double>("CombatScore")
                        .HasColumnType("REAL");

                    b.Property<int?>("CompilationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EstimatedDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstKillTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationDemoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeadshotCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HighlightId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("KillCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastKillTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("ScoreBreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SelectedByUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SelectedForCompilation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponSequenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "GenerationDemoId", "HighlightId")
                        .IsUnique();

                    b.ToTable("GenerationHighlights");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalKills")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "SteamId")
                        .IsUnique();

                    b.ToTable("GenerationPlayers");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationArtifact", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Artifacts")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationDemo", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Demos")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEffectPlan", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.GenerationHighlight", "Highlight")
                        .WithMany()
                        .HasForeignKey("GenerationHighlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("EffectPlans")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Highlight");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationEvent", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Events")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationHighlight", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Highlights")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.GenerationPlayer", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Players")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Payment", b =>
                {
                    b.HasOne("Cs2Highlight.Web.Domain.Generation", "Generation")
                        .WithMany("Payments")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Cs2Highlight.Web.Domain.Generation", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Demos");

                    b.Navigation("EffectPlans");

                    b.Navigation("Events");

                    b.Navigation("Highlights");

                    b.Navigation("Payments");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
